### ISSUE TITLE
Setup testing for developers

### ISSUE THREAD

**Issue by MartinSvarrer** [MartinSvarrer/sitecore-ui#4]
A developer is responsible for writing unit tests and integration tests in JavaScript. We expect a majority our tests to be unit tests. We define a unit as a component.

We should re-use the test setup from material-ui as it is quite robust, as much as possible. Some info can be found at https://github.com/callemall/material-ui/tree/master/test.

- [x] Write unit tests for Button component to dispay how we write unit tests
- [x] Write integration tests for Button component to display how we write integration tests
- [x] Copy the test set up from Material-UI
- [x] VSCode integration

**Comment by MaxReimerNielsen** [comment]
@MartinSvarrer and I decided, that real integration tests should not be added at the current stage, since this is a components library, and right now, we don't have anything that is communicating with eachother. We were thinking, that integration tests should mostly be for applications with Flux/Redux etc.

Besides the tasks on this issue, I have also added Karma browser testing, VSCode integration and much more. Take a look at [README](https://github.com/MartinSvarrer/sitecore-ui) for more details.
